import type { Metadata } from "next";
import Navbar from "@/components/common/Navbar";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Serinity - Official Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen"
      >
        <Navbar/>
        <main>{children}</main>
      </body>
    </html>
  );
}
