import type { Metadata } from "next";
import { Providers } from "./providers";
import Navbar from "@/components/common/navbar/Navbar";
import Footer from "@/components/common/footer/Footer";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Serinity - Official Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen"
      >
        <Providers>
          <Navbar/>
          <main>{children}</main>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
